=== hkunz/createswf/scripts/doctypedef.dtd
<!DOCTYPE movie [

<!ENTITY author "Harry Kunz">
<!ENTITY date "16/07/2012">

<!ELEMENT movie (player?, quality?, mode?, name?, library?)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT player (#PCDATA)>
<!ELEMENT mode (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT library (sprites?, movieclips?, bitmaps?, sounds?, binaries?)>

<!ATTLIST movie width CDATA "640">
<!ATTLIST movie height CDATA "480">
<!ATTLIST movie fps CDATA "24">
<!ATTLIST movie background CDATA "#ffffff">

<!ELEMENT sprites (spr+)>
<!ELEMENT spr (object*)>
<!ELEMENT object (#PCDATA)>

<!ATTLIST spr class ID #REQUIRED>
<!ATTLIST spr name CDATA #IMPLIED>
<!ATTLIST spr path CDATA #IMPLIED>
<!ATTLIST spr x CDATA "0">
<!ATTLIST spr y CDATA "0">
<!ATTLIST spr alpha CDATA "1.0">
<!ATTLIST spr visible (true|false|0|1) "true">

<!ATTLIST object name ID #IMPLIED>
<!ATTLIST object path CDATA #IMPLIED>
<!ATTLIST object x CDATA "0">
<!ATTLIST object y CDATA "0">
<!ATTLIST object alpha CDATA "1.0">
<!ATTLIST object visible (true|false|0|1) "true">

<!ELEMENT movieclips (mc+)>
<!ELEMENT mc (frame*)>
<!ELEMENT frame (#PCDATA)>

<!ATTLIST mc class ID #REQUIRED>
<!ATTLIST mc name CDATA #IMPLIED>
<!ATTLIST mc path CDATA #IMPLIED>
<!ATTLIST mc x CDATA "0">
<!ATTLIST mc y CDATA "0">
<!ATTLIST mc alpha CDATA "1.0">
<!ATTLIST mc visible (true|false|0|1) "true">
<!ATTLIST mc fps CDATA "12">

<!ATTLIST frame name ID #IMPLIED>
<!ATTLIST frame path CDATA #IMPLIED>
<!ATTLIST frame x CDATA "0">
<!ATTLIST frame y CDATA "0">
<!ATTLIST frame alpha CDATA "1.0">
<!ATTLIST frame visible (true|false|0|1) "true">

<!ELEMENT bitmaps (bmp*)>
<!ELEMENT bmp (#PCDATA)>
<!ELEMENT sounds (snd*)>
<!ELEMENT snd (#PCDATA)>
<!ELEMENT binaries (bin*)>
<!ELEMENT bin (#PCDATA)>

<!ATTLIST bmp class ID #REQUIRED>
<!ATTLIST bmp name CDATA #IMPLIED>
<!ATTLIST bmp path CDATA #REQUIRED>

<!ATTLIST snd class ID #REQUIRED>
<!ATTLIST snd name CDATA #IMPLIED>
<!ATTLIST snd path CDATA #REQUIRED>

<!ATTLIST bin class ID #REQUIRED>
<!ATTLIST bin name CDATA #IMPLIED>
<!ATTLIST bin path CDATA #REQUIRED>

]>

=== hkunz/createswf/scripts/definition.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE movie SYSTEM "doctypedef.dtd">

<movie width="320" height="240" fps="12" background="#CCCCCC">
	<player>10.2</player>
	<quality>80</quality>
	<mode>1</mode>
	<name>assets.swf</name>
	<library>
		<sprites>
			<spr class="emptysprite" />
			<spr class="spr1" path="base/path/image.png" x="20" y="-10" alpha="0.2" />
			<spr class="spr2" path="base/path/">
				<object name="name1" path="path/image1.jpg" x="10" y="5" alpha="" visible="false" />
				<object name="name2" path="path/image2.png" y="5" alpha="1.0" />
				<object name="name3" path="path/image3.gif" alpha="0.5" />
			</spr>
		</sprites>
		<movieclips>
			<mc class="emptymovieclip" />
			<mc class="mc1" path="base/path/image.png" />
			<mc class="mc2" path="base/path/">
				<frame name="name4" path="path/image1.jpg" x="10" y="5" alpha="" visible="false" />
				<frame name="name5" path="path/image2.png" y="5" alpha="1.0" />
				<frame name="name6" path="path/image3.gif" alpha="0.5" />
			</mc>
		</movieclips>
		<bitmaps>
			<bmp class="bmp1" path="path/bmp1.jpg" />
			<bmp class="bmp2" path="path/bmp1.png" />
			<bmp class="bmp3" path="path/bmp1.gif" />
		</bitmaps>
		<sounds>
			<snd class="snd1" path="path/sound.mp3" />
			<snd class="snd2" path="path/sound.wav" />
			<snd class="snd3" path="path/sound.ogg" />
		</sounds>
		<binaries>
			<bin class="bin1" path="path/image.bmp" />
			<bin class="bin2" path="path/sound.ogg" />
			<bin class="bin3" path="path/movie.swf" />
			<bin class="bin4" path="path/document.doc" />
			<bin class="bin5" path="path/prog.exe" />
			<bin class="bin6" path="path/whateverfile" />
		</binaries>
	</library>
</movie>
